### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function split()

### ISSUE THREAD

**Issue by wellington1993** [mariuz/firebirdwebadmin#17]
Hi, 
Other PHP 7 issue:
`
[Thu Jul 13 09:50:38.446142 2017] [:error] [pid 9682] [client 127.0.0.1:38358] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/html/firebirdwebadmin/inc/debug_funcs.inc.php:27\nStack trace:\n#0 /var/www/html/firebirdwebadmin/views/footer.php(30): show_time_consumption('0.44567700 1499...', '0.44611700 1499...')\n#1 /var/www/html/firebirdwebadmin/inc/script_end.inc.php(80): require_once('/var/www/html/f...')\n#2 /var/www/html/firebirdwebadmin/sql.php(230): require('/var/www/html/f...')\n#3 {main}\n  thrown in /var/www/html/firebirdwebadmin/inc/debug_funcs.inc.php on line 27, referer: http://localhost/firebirdwebadmin/sql.php
`

**Comment by mariuz** [comment]
https://github.com/mariuz/firebirdwebadmin/commit/a42292b07a26c3a0df3e339f126b77b8251a5c73
