### ISSUE TITLE
Your php installation misses the interbase support!

### ISSUE THREAD

**Issue by DanchoVENT** [mariuz/firebirdwebadmin#33]
I use 7.2.34 php version, where have interbase included. I try with other new versions, and no result.

This is the error i get every time:

Warning: Use of undefined constant IBASE_COMMITTED - assumed 'IBASE_COMMITTED' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 137

Warning: Use of undefined constant IBASE_NOWAIT - assumed 'IBASE_NOWAIT' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 137

Warning: Use of undefined constant IBASE_READ - assumed 'IBASE_READ' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 137

Warning: Use of undefined constant IBASE_COMMITTED - assumed 'IBASE_COMMITTED' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 138

Warning: Use of undefined constant IBASE_NOWAIT - assumed 'IBASE_NOWAIT' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 138

Warning: Use of undefined constant IBASE_WRITE - assumed 'IBASE_WRITE' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\inc\configuration.inc.php on line 138
Your php installation misses the interbase support!
Recompile php and configure --with-interbase[=DIR]
or edit your php.ini to load interbase.so respectively interbase.dll.

**Comment by Fedesin** [comment]
how do you repair this error??
