### ISSUE TITLE
i cant install Firebird web admin in php 8.1

### ISSUE THREAD

**Issue by Fedesin** [mariuz/firebirdwebadmin#38]
Hello,

I have many errors in the code when i try to install Firebird web admin with a version of php 8.1.

Can anyone make this install php 8.1?

**Comment by Fedesin** [comment]
[php:error] [pid 31419] [client 127.0.0.1:46776] PHP Fatal error:  Uncaught Error: Undefined constant "IBASE_COMMITTED" in /var/www/html/firebirdwebadmin/inc/configuration.inc.php:137\nStack trace:\n#0 /var/www/html/firebirdwebadmin/inc/script_start.inc.php(8): require()\n#1 /var/www/html/firebirdwebadmin/database.php(9): require('...')\n#2 {main}\n  thrown in /var/www/html/firebirdwebadmin/inc/configuration.inc.php on line 137

i have this error

**Comment by mariuz** [comment]
you need to install  https://github.com/FirebirdSQL/php-firebird

**Comment by Fedesin** [comment]
> you need to install https://github.com/FirebirdSQL/php-firebird

okay, thanks you. Now i have this error:

[Fri Sep 22 11:30:25.454584 2023] [php:error] [pid 11013] [client 127.0.0.1:52230] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function error_handler(), 4 passed in /var/www/html/firebirdwebadmin/inc/session.inc.php on line 81 and exactly 5 expected in /var/www/html/firebirdwebadmin/inc/functions.inc.php:1094\nStack trace:\n#0 /var/www/html/firebirdwebadmin/inc/session.inc.php(81): error_handler()\n#1 /var/www/html/firebirdwebadmin/inc/script_start.inc.php(36): initialize_session()\n#2 /var/www/html/firebirdwebadmin/database.php(9): require('...')\n#3 {main}\n  thrown in /var/www/html/firebirdwebadmin/inc/functions.inc.php on line 1094
